-- Auto-generisano — svi modeli × zvanične boje, cena i količina 0
-- Pokreni u Supabase SQL Editor (preskače postojeće model+boja)

insert into public.poklopci_artikli (naziv, model, boja, kolicina, nabavna_cena, prodajna_cena)
select v.naziv, v.model, v.boja, v.kolicina, v.nabavna, v.prodajna
from (values
  ('iPhone 11 — Crna', 'iPhone 11', 'Crna', 0, 0, 0),
  ('iPhone 11 — Bela', 'iPhone 11', 'Bela', 0, 0, 0),
  ('iPhone 11 — Ljubičasta', 'iPhone 11', 'Ljubičasta', 0, 0, 0),
  ('iPhone 11 — Zelena', 'iPhone 11', 'Zelena', 0, 0, 0),
  ('iPhone 11 — Žuta', 'iPhone 11', 'Žuta', 0, 0, 0),
  ('iPhone 11 — Crvena', 'iPhone 11', 'Crvena', 0, 0, 0),
  ('iPhone 11 Pro — Siva', 'iPhone 11 Pro', 'Siva', 0, 0, 0),
  ('iPhone 11 Pro — Srebrna', 'iPhone 11 Pro', 'Srebrna', 0, 0, 0),
  ('iPhone 11 Pro — Zlatna', 'iPhone 11 Pro', 'Zlatna', 0, 0, 0),
  ('iPhone 11 Pro — Tamno zelena', 'iPhone 11 Pro', 'Tamno zelena', 0, 0, 0),
  ('iPhone 11 Pro Max — Siva', 'iPhone 11 Pro Max', 'Siva', 0, 0, 0),
  ('iPhone 11 Pro Max — Srebrna', 'iPhone 11 Pro Max', 'Srebrna', 0, 0, 0),
  ('iPhone 11 Pro Max — Zlatna', 'iPhone 11 Pro Max', 'Zlatna', 0, 0, 0),
  ('iPhone 11 Pro Max — Tamno zelena', 'iPhone 11 Pro Max', 'Tamno zelena', 0, 0, 0),
  ('iPhone 12 mini — Crna', 'iPhone 12 mini', 'Crna', 0, 0, 0),
  ('iPhone 12 mini — Bela', 'iPhone 12 mini', 'Bela', 0, 0, 0),
  ('iPhone 12 mini — Plava', 'iPhone 12 mini', 'Plava', 0, 0, 0),
  ('iPhone 12 mini — Zelena', 'iPhone 12 mini', 'Zelena', 0, 0, 0),
  ('iPhone 12 mini — Ljubičasta', 'iPhone 12 mini', 'Ljubičasta', 0, 0, 0),
  ('iPhone 12 mini — Crvena', 'iPhone 12 mini', 'Crvena', 0, 0, 0),
  ('iPhone 12 — Crna', 'iPhone 12', 'Crna', 0, 0, 0),
  ('iPhone 12 — Bela', 'iPhone 12', 'Bela', 0, 0, 0),
  ('iPhone 12 — Plava', 'iPhone 12', 'Plava', 0, 0, 0),
  ('iPhone 12 — Zelena', 'iPhone 12', 'Zelena', 0, 0, 0),
  ('iPhone 12 — Ljubičasta', 'iPhone 12', 'Ljubičasta', 0, 0, 0),
  ('iPhone 12 — Crvena', 'iPhone 12', 'Crvena', 0, 0, 0),
  ('iPhone 12 Pro — Grafit', 'iPhone 12 Pro', 'Grafit', 0, 0, 0),
  ('iPhone 12 Pro — Srebrna', 'iPhone 12 Pro', 'Srebrna', 0, 0, 0),
  ('iPhone 12 Pro — Zlatna', 'iPhone 12 Pro', 'Zlatna', 0, 0, 0),
  ('iPhone 12 Pro — Morsko plava', 'iPhone 12 Pro', 'Morsko plava', 0, 0, 0),
  ('iPhone 12 Pro Max — Grafit', 'iPhone 12 Pro Max', 'Grafit', 0, 0, 0),
  ('iPhone 12 Pro Max — Srebrna', 'iPhone 12 Pro Max', 'Srebrna', 0, 0, 0),
  ('iPhone 12 Pro Max — Zlatna', 'iPhone 12 Pro Max', 'Zlatna', 0, 0, 0),
  ('iPhone 12 Pro Max — Morsko plava', 'iPhone 12 Pro Max', 'Morsko plava', 0, 0, 0),
  ('iPhone 13 mini — Midnight', 'iPhone 13 mini', 'Midnight', 0, 0, 0),
  ('iPhone 13 mini — Starlight', 'iPhone 13 mini', 'Starlight', 0, 0, 0),
  ('iPhone 13 mini — Plava', 'iPhone 13 mini', 'Plava', 0, 0, 0),
  ('iPhone 13 mini — Roze', 'iPhone 13 mini', 'Roze', 0, 0, 0),
  ('iPhone 13 mini — Zelena', 'iPhone 13 mini', 'Zelena', 0, 0, 0),
  ('iPhone 13 mini — Crvena', 'iPhone 13 mini', 'Crvena', 0, 0, 0),
  ('iPhone 13 — Midnight', 'iPhone 13', 'Midnight', 0, 0, 0),
  ('iPhone 13 — Starlight', 'iPhone 13', 'Starlight', 0, 0, 0),
  ('iPhone 13 — Plava', 'iPhone 13', 'Plava', 0, 0, 0),
  ('iPhone 13 — Roze', 'iPhone 13', 'Roze', 0, 0, 0),
  ('iPhone 13 — Zelena', 'iPhone 13', 'Zelena', 0, 0, 0),
  ('iPhone 13 — Crvena', 'iPhone 13', 'Crvena', 0, 0, 0),
  ('iPhone 13 Pro — Grafit', 'iPhone 13 Pro', 'Grafit', 0, 0, 0),
  ('iPhone 13 Pro — Zlatna', 'iPhone 13 Pro', 'Zlatna', 0, 0, 0),
  ('iPhone 13 Pro — Srebrna', 'iPhone 13 Pro', 'Srebrna', 0, 0, 0),
  ('iPhone 13 Pro — Svetlo plava', 'iPhone 13 Pro', 'Svetlo plava', 0, 0, 0),
  ('iPhone 13 Pro — Tamno zelena', 'iPhone 13 Pro', 'Tamno zelena', 0, 0, 0),
  ('iPhone 13 Pro Max — Grafit', 'iPhone 13 Pro Max', 'Grafit', 0, 0, 0),
  ('iPhone 13 Pro Max — Zlatna', 'iPhone 13 Pro Max', 'Zlatna', 0, 0, 0),
  ('iPhone 13 Pro Max — Srebrna', 'iPhone 13 Pro Max', 'Srebrna', 0, 0, 0),
  ('iPhone 13 Pro Max — Svetlo plava', 'iPhone 13 Pro Max', 'Svetlo plava', 0, 0, 0),
  ('iPhone 13 Pro Max — Tamno zelena', 'iPhone 13 Pro Max', 'Tamno zelena', 0, 0, 0),
  ('iPhone 14 — Midnight', 'iPhone 14', 'Midnight', 0, 0, 0),
  ('iPhone 14 — Starlight', 'iPhone 14', 'Starlight', 0, 0, 0),
  ('iPhone 14 — Plava', 'iPhone 14', 'Plava', 0, 0, 0),
  ('iPhone 14 — Ljubičasta', 'iPhone 14', 'Ljubičasta', 0, 0, 0),
  ('iPhone 14 — Žuta', 'iPhone 14', 'Žuta', 0, 0, 0),
  ('iPhone 14 — Crvena', 'iPhone 14', 'Crvena', 0, 0, 0),
  ('iPhone 14 Plus — Midnight', 'iPhone 14 Plus', 'Midnight', 0, 0, 0),
  ('iPhone 14 Plus — Starlight', 'iPhone 14 Plus', 'Starlight', 0, 0, 0),
  ('iPhone 14 Plus — Plava', 'iPhone 14 Plus', 'Plava', 0, 0, 0),
  ('iPhone 14 Plus — Ljubičasta', 'iPhone 14 Plus', 'Ljubičasta', 0, 0, 0),
  ('iPhone 14 Plus — Žuta', 'iPhone 14 Plus', 'Žuta', 0, 0, 0),
  ('iPhone 14 Plus — Crvena', 'iPhone 14 Plus', 'Crvena', 0, 0, 0),
  ('iPhone 14 Pro — Crna', 'iPhone 14 Pro', 'Crna', 0, 0, 0),
  ('iPhone 14 Pro — Srebrna', 'iPhone 14 Pro', 'Srebrna', 0, 0, 0),
  ('iPhone 14 Pro — Zlatna', 'iPhone 14 Pro', 'Zlatna', 0, 0, 0),
  ('iPhone 14 Pro — Deep Purple', 'iPhone 14 Pro', 'Deep Purple', 0, 0, 0),
  ('iPhone 14 Pro Max — Crna', 'iPhone 14 Pro Max', 'Crna', 0, 0, 0),
  ('iPhone 14 Pro Max — Srebrna', 'iPhone 14 Pro Max', 'Srebrna', 0, 0, 0),
  ('iPhone 14 Pro Max — Zlatna', 'iPhone 14 Pro Max', 'Zlatna', 0, 0, 0),
  ('iPhone 14 Pro Max — Deep Purple', 'iPhone 14 Pro Max', 'Deep Purple', 0, 0, 0),
  ('iPhone 15 — Crna', 'iPhone 15', 'Crna', 0, 0, 0),
  ('iPhone 15 — Plava', 'iPhone 15', 'Plava', 0, 0, 0),
  ('iPhone 15 — Zelena', 'iPhone 15', 'Zelena', 0, 0, 0),
  ('iPhone 15 — Žuta', 'iPhone 15', 'Žuta', 0, 0, 0),
  ('iPhone 15 — Roze', 'iPhone 15', 'Roze', 0, 0, 0),
  ('iPhone 15 Plus — Crna', 'iPhone 15 Plus', 'Crna', 0, 0, 0),
  ('iPhone 15 Plus — Plava', 'iPhone 15 Plus', 'Plava', 0, 0, 0),
  ('iPhone 15 Plus — Zelena', 'iPhone 15 Plus', 'Zelena', 0, 0, 0),
  ('iPhone 15 Plus — Žuta', 'iPhone 15 Plus', 'Žuta', 0, 0, 0),
  ('iPhone 15 Plus — Roze', 'iPhone 15 Plus', 'Roze', 0, 0, 0),
  ('iPhone 15 Pro — Black Titanium', 'iPhone 15 Pro', 'Black Titanium', 0, 0, 0),
  ('iPhone 15 Pro — White Titanium', 'iPhone 15 Pro', 'White Titanium', 0, 0, 0),
  ('iPhone 15 Pro — Blue Titanium', 'iPhone 15 Pro', 'Blue Titanium', 0, 0, 0),
  ('iPhone 15 Pro — Natural Titanium', 'iPhone 15 Pro', 'Natural Titanium', 0, 0, 0),
  ('iPhone 15 Pro Max — Black Titanium', 'iPhone 15 Pro Max', 'Black Titanium', 0, 0, 0),
  ('iPhone 15 Pro Max — White Titanium', 'iPhone 15 Pro Max', 'White Titanium', 0, 0, 0),
  ('iPhone 15 Pro Max — Blue Titanium', 'iPhone 15 Pro Max', 'Blue Titanium', 0, 0, 0),
  ('iPhone 15 Pro Max — Natural Titanium', 'iPhone 15 Pro Max', 'Natural Titanium', 0, 0, 0),
  ('iPhone 16 — Crna', 'iPhone 16', 'Crna', 0, 0, 0),
  ('iPhone 16 — Bela', 'iPhone 16', 'Bela', 0, 0, 0),
  ('iPhone 16 — Roze', 'iPhone 16', 'Roze', 0, 0, 0),
  ('iPhone 16 — Tirkizna', 'iPhone 16', 'Tirkizna', 0, 0, 0),
  ('iPhone 16 — Tamno plava', 'iPhone 16', 'Tamno plava', 0, 0, 0),
  ('iPhone 16 Plus — Crna', 'iPhone 16 Plus', 'Crna', 0, 0, 0),
  ('iPhone 16 Plus — Bela', 'iPhone 16 Plus', 'Bela', 0, 0, 0),
  ('iPhone 16 Plus — Roze', 'iPhone 16 Plus', 'Roze', 0, 0, 0),
  ('iPhone 16 Plus — Tirkizna', 'iPhone 16 Plus', 'Tirkizna', 0, 0, 0),
  ('iPhone 16 Plus — Tamno plava', 'iPhone 16 Plus', 'Tamno plava', 0, 0, 0),
  ('iPhone 16 Pro — Black Titanium', 'iPhone 16 Pro', 'Black Titanium', 0, 0, 0),
  ('iPhone 16 Pro — White Titanium', 'iPhone 16 Pro', 'White Titanium', 0, 0, 0),
  ('iPhone 16 Pro — Natural Titanium', 'iPhone 16 Pro', 'Natural Titanium', 0, 0, 0),
  ('iPhone 16 Pro — Champagne', 'iPhone 16 Pro', 'Champagne', 0, 0, 0),
  ('iPhone 16 Pro Max — Black Titanium', 'iPhone 16 Pro Max', 'Black Titanium', 0, 0, 0),
  ('iPhone 16 Pro Max — White Titanium', 'iPhone 16 Pro Max', 'White Titanium', 0, 0, 0),
  ('iPhone 16 Pro Max — Natural Titanium', 'iPhone 16 Pro Max', 'Natural Titanium', 0, 0, 0),
  ('iPhone 16 Pro Max — Champagne', 'iPhone 16 Pro Max', 'Champagne', 0, 0, 0),
  ('iPhone 16e — Crna', 'iPhone 16e', 'Crna', 0, 0, 0),
  ('iPhone 16e — Bela', 'iPhone 16e', 'Bela', 0, 0, 0),
  ('iPhone 17 — Crna', 'iPhone 17', 'Crna', 0, 0, 0),
  ('iPhone 17 — Bela', 'iPhone 17', 'Bela', 0, 0, 0),
  ('iPhone 17 — Svetlo plava', 'iPhone 17', 'Svetlo plava', 0, 0, 0),
  ('iPhone 17 — Zelena', 'iPhone 17', 'Zelena', 0, 0, 0),
  ('iPhone 17 — Ljubičasta', 'iPhone 17', 'Ljubičasta', 0, 0, 0),
  ('iPhone 17 Air — Plava', 'iPhone 17 Air', 'Plava', 0, 0, 0),
  ('iPhone 17 Air — Zlatna', 'iPhone 17 Air', 'Zlatna', 0, 0, 0),
  ('iPhone 17 Air — Bela', 'iPhone 17 Air', 'Bela', 0, 0, 0),
  ('iPhone 17 Air — Crna', 'iPhone 17 Air', 'Crna', 0, 0, 0),
  ('iPhone 17 Pro — Srebrna', 'iPhone 17 Pro', 'Srebrna', 0, 0, 0),
  ('iPhone 17 Pro — Narandžasta', 'iPhone 17 Pro', 'Narandžasta', 0, 0, 0),
  ('iPhone 17 Pro — Tamno plava', 'iPhone 17 Pro', 'Tamno plava', 0, 0, 0),
  ('iPhone 17 Pro Max — Srebrna', 'iPhone 17 Pro Max', 'Srebrna', 0, 0, 0),
  ('iPhone 17 Pro Max — Narandžasta', 'iPhone 17 Pro Max', 'Narandžasta', 0, 0, 0),
  ('iPhone 17 Pro Max — Tamno plava', 'iPhone 17 Pro Max', 'Tamno plava', 0, 0, 0)
) as v(naziv, model, boja, kolicina, nabavna, prodajna)
where not exists (
  select 1 from public.poklopci_artikli a
  where a.model = v.model and a.boja = v.boja
);
